/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screen;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import lexer.Lexer;
import lexer.Token;
import lexer.TokenType;
import parser.Parser;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import parser.Nodos;

/**
 *
 * @author jeane
 */
public class Principal extends javax.swing.JFrame {    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    JTextArea txtLineas = new JTextArea("1");   
    private Nodos ultimoArbol = null;
    private ArrayList<String> ultimaDerivacion = new ArrayList<>();
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
        setContentPane(jPanel1);
        
        //Tabla ----------------------
        tblLexemas.getTableHeader().setForeground(Color.white );
        tblLexemas.getTableHeader().setFont(
            new java.awt.Font("Baskerville Old Face", java.awt.Font.BOLD, 24));
        
       tblLexemas.getTableHeader().setBackground(new Color(76, 122, 76));
       tblLexemas.getTableHeader().setPreferredSize(
            new Dimension(tblLexemas.getTableHeader().getPreferredSize().width,40)
        );
       
        scpLexemas.setBorder(BorderFactory.createLineBorder(new Color(76, 122, 76),2));
        scpLexemas.setViewportBorder(null);
        
        //Logo ----------------------
        java.net.URL url = getClass().getResource("/screen/logoMol.png"); 
        ImageIcon icon = new ImageIcon(url);
        Image imagenEscalada = icon.getImage().getScaledInstance(
                100,
                100,
                Image.SCALE_AREA_AVERAGING
        );  
        
        lblLogo.setIcon(new ImageIcon(imagenEscalada));
        
        //Área de código ----------------------
        txtCodigo.getDocument().addDocumentListener(
            new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    actualizarLineas();
                    btnLimpiar.setEnabled(true);
                    
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    actualizarLineas();
                    
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    actualizarLineas();
                    btnLimpiar.setEnabled(true);
                }
            }
        );
        
        scpInput.setBorder(BorderFactory.createLineBorder(new Color(76, 122, 76),2));
        scpInput.setViewportBorder(null);
        
        
        //Contador de lineas ----------------------
        txtLineas.setEditable(false);
        scpInput.setRowHeaderView(txtLineas);
        txtLineas.setFont(new java.awt.Font("Cascadia Code",java.awt.Font.BOLD,22));
        txtLineas.setForeground(new Color(132,164,132));
        txtLineas.setFocusable(false);
        txtLineas.setPreferredSize(
            new Dimension(38,txtLineas.getPreferredSize().height)                            
        );
        
        scpOutput.setBorder(BorderFactory.createLineBorder(new Color(132,164,132),2));
        scpOutput.setViewportBorder(null);
        scpOutput.getViewport().setBackground(new Color(132,164,132));
        
        //Logo ----------------------
        java.net.URL url2 = getClass().getResource("/screen/miguel.png"); 
        System.out.println(url2);
        ImageIcon icon2 = new ImageIcon(url2);
        Image imagenEscalada2 = icon2.getImage().getScaledInstance(
                112,
                154,
                Image.SCALE_AREA_AVERAGING
        );  
        
        lblMiguel.setIcon(new ImageIcon(imagenEscalada2));  


    }//constructor
    
    private void actualizarLineas() {
        int total = txtCodigo.getLineCount();
        StringBuilder sb = new StringBuilder();

        for(int i = 1; i <= total; i++) {
            sb.append(i).append("\n");
        }
        txtLineas.setText(sb.toString());
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pOutput = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnDeriv = new javax.swing.JButton();
        btnArbol = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        scpOutput = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JLabel();
        lblMiguel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        scpLexemas = new javax.swing.JScrollPane();
        tblLexemas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        scpInput = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(132, 164, 132));

        jPanel1.setBackground(new java.awt.Color(253, 255, 254));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(248, 253, 248));
        jPanel2.setPreferredSize(new java.awt.Dimension(957, 100));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setBackground(new java.awt.Color(76, 122, 76));
        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 122, 76));
        jLabel2.setText("MolCompiler");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(248, 253, 248));
        jPanel4.setPreferredSize(new java.awt.Dimension(957, 200));

        pOutput.setBackground(new java.awt.Color(132, 164, 132));

        jPanel7.setBackground(new java.awt.Color(76, 122, 76));
        jPanel7.setPreferredSize(new java.awt.Dimension(957, 40));

        btnDeriv.setBackground(new java.awt.Color(248, 253, 248));
        btnDeriv.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnDeriv.setForeground(new java.awt.Color(76, 122, 76));
        btnDeriv.setText("Derivación");
        btnDeriv.setEnabled(false);
        btnDeriv.addActionListener(this::btnDerivActionPerformed);

        btnArbol.setBackground(new java.awt.Color(248, 253, 248));
        btnArbol.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnArbol.setForeground(new java.awt.Color(76, 122, 76));
        btnArbol.setText("Árbol sintáctico");
        btnArbol.setEnabled(false);
        btnArbol.addActionListener(this::btnArbolActionPerformed);

        btnRun.setBackground(new java.awt.Color(248, 253, 248));
        btnRun.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        btnRun.setForeground(new java.awt.Color(76, 122, 76));
        btnRun.setText("▶");
        btnRun.setToolTipText("");
        btnRun.setAlignmentY(0.0F);
        btnRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRun.addActionListener(this::btnRunActionPerformed);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Output");

        btnLimpiar.setBackground(new java.awt.Color(248, 253, 248));
        btnLimpiar.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(76, 122, 76));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.setAlignmentY(0.0F);
        btnLimpiar.setEnabled(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeriv, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeriv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        scpOutput.setBackground(new java.awt.Color(132, 164, 132));
        scpOutput.setBorder(null);
        scpOutput.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtOutput.setBackground(new java.awt.Color(132, 164, 132));
        txtOutput.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        txtOutput.setForeground(new java.awt.Color(255, 255, 255));
        txtOutput.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        scpOutput.setViewportView(txtOutput);

        javax.swing.GroupLayout pOutputLayout = new javax.swing.GroupLayout(pOutput);
        pOutput.setLayout(pOutputLayout);
        pOutputLayout.setHorizontalGroup(
            pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMiguel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pOutputLayout.setVerticalGroup(
            pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOutputLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pOutputLayout.createSequentialGroup()
                        .addComponent(scpOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(lblMiguel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(248, 253, 248));
        jPanel5.setPreferredSize(new java.awt.Dimension(450, 331));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        tblLexemas.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        tblLexemas.setForeground(new java.awt.Color(51, 51, 51));
        tblLexemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO", "LEXEMA"
            }
        ));
        tblLexemas.setFocusable(false);
        tblLexemas.setIntercellSpacing(new java.awt.Dimension(20, 0));
        tblLexemas.setRowHeight(40);
        tblLexemas.setRowSelectionAllowed(false);
        tblLexemas.setShowGrid(true);
        scpLexemas.setViewportView(tblLexemas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        jPanel5.add(scpLexemas, gridBagConstraints);

        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(248, 253, 248));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        txtCodigo.setColumns(20);
        txtCodigo.setFont(new java.awt.Font("Cascadia Code", 0, 22)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigo.setRows(5);
        scpInput.setViewportView(txtCodigo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 0);
        jPanel6.add(scpInput, gridBagConstraints);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbolActionPerformed
        if (ultimoArbol != null) {
            new Arbol(this, ultimoArbol).setVisible(true);
        }
    }//GEN-LAST:event_btnArbolActionPerformed

    private void btnDerivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivActionPerformed
        if (!ultimaDerivacion.isEmpty()) {
            new Derivacion(this, ultimaDerivacion).setVisible(true);
        }
    }//GEN-LAST:event_btnDerivActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        ejecutarAnalisis();
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        btnArbol.setEnabled(false);
        btnDeriv.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    
private void ejecutarAnalisis() {
        String input = txtCodigo.getText().trim();

        // Limpiar tabla y output
        DefaultTableModel modelo = (DefaultTableModel) tblLexemas.getModel();
        modelo.setRowCount(0);
        txtOutput.setText("");
        
        if (input.isEmpty()) return;

        // 1. Lexico
        List<Token> listaDeTokens = new ArrayList<>();
        List<String> erroresLexicosGlobales = new ArrayList<>(); // Aquí guardaremos los errores de todas las líneas
        
        String[] lineas = input.split("\n", -1); 
        
        for (int numLinea = 1; numLinea <= lineas.length; numLinea++) {
            String linea = lineas[numLinea - 1];
            if (linea.isBlank()) continue;

            Lexer lexer = new Lexer(linea);
            Token tok = lexer.getNextToken();

            // Metemos los tokens válidos a la tabla y a la lista
            while (tok.getType() != TokenType.EOF) {
                listaDeTokens.add(tok);
                modelo.addRow(new Object[]{tok.getType().toString(), tok.getLexeme()});
                tok = lexer.getNextToken();
            }
            
            // El lexer revisa errores
            if (!lexer.getErroresLexicos().isEmpty()) {
                for (String err : lexer.getErroresLexicos()) {
                    // Linea con error
                    erroresLexicosGlobales.add("Línea " + numLinea + " - " + err);
                }
            }
        }

        // Errores lexicos de arrastre
        // Si jhay error se aborta
        if (!erroresLexicosGlobales.isEmpty()) {
            StringBuilder sb = new StringBuilder("<html><font color='#FFD6D6'><b>--- ERRORES LÉXICOS ENCONTRADOS ---</b><br>");
            sb.append("<div style='width:1100px;'>");
            
            for (String err : erroresLexicosGlobales) {
                sb.append(err).append("<br>");
            }
            sb.append("<br>Análisis abortado: No se puede iniciar el análisis sintáctico debido a errores léxicos previos.</font></html>");
            txtOutput.setText(sb.toString());
            
            ultimoArbol = null;
            ultimaDerivacion.clear();
            return; // Detenemos la ejecución, el Parser no arranca
        }

        // 2. Tokens para el parser
        ArrayList<Token> tokensParaParser = new ArrayList<>();
        for (Token t : listaDeTokens) {
            if (t.getType() != TokenType.EOF) {
                tokensParaParser.add(t);
            }
        }
        tokensParaParser.add(new Token(TokenType.EOF, "")); 

        // SINTACTICO
        Parser parser = new Parser(tokensParaParser);
        parser.parse(); //Modo panico

        // Errores sintacticos de arrastre
        if (!parser.getErroresSintacticos().isEmpty()) {
            StringBuilder sb = new StringBuilder("<html><font color='#FFF4CC'><b>--- ERRORES SINTÁCTICOS ENCONTRADOS ---</b><br>");
            for (String err : parser.getErroresSintacticos()) {
                sb.append(err).append("<br>");
            }
            sb.append("<br> Análisis sintáctico finalizado con errores.</font></html>");
            txtOutput.setText(sb.toString());
            ultimoArbol = parser.getRaiz();
            ultimaDerivacion = parser.getDerivacion();
            
        } else {
            ultimoArbol = parser.getRaiz();
            ultimaDerivacion = parser.getDerivacion();
            
            //Semantico
            semantic.SemanticAnalyzer semantico = new semantic.SemanticAnalyzer();
            
            // Le pasamos la raíz del árbol (AST) que construyó el Parser
            semantico.analizar(parser.getRaiz());
            
            if (!semantico.getErroresSemanticos().isEmpty()) {
                StringBuilder sb = new StringBuilder("<html><font color='#FFA07A'><b>--- ERRORES SEMÁNTICOS ENCONTRADOS ---</b><br>");
                for (String err : semantico.getErroresSemanticos()) {
                    sb.append(err).append("<br>");
                }
                sb.append("<br> Análisis finalizado con errores en la lógica química.</font></html>");
                txtOutput.setText(sb.toString());
                
            } else {
                StringBuilder sb = new StringBuilder("<html><font color='#90EE90'><b>Análisis completado con éxito.</b><br>La estructura y la química son correctas.<br><br>");
                
                for (String res : semantico.getResultados()) {
                    sb.append("<font color='#FFFFFF'><b>▶ ").append(res).append("</b></font><br>");
                }
                
                sb.append("</font></html>");
                txtOutput.setText(sb.toString());
            }

            btnArbol.setEnabled(true);             
            btnDeriv.setEnabled(true);
    }
}
    
    private void limpiar() {
        txtCodigo.setText("");
        DefaultTableModel modelo = (DefaultTableModel) tblLexemas.getModel();
        modelo.setRowCount(0);
        txtOutput.setText("");
    }
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArbol;
    private javax.swing.JButton btnDeriv;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMiguel;
    private javax.swing.JPanel pOutput;
    private javax.swing.JScrollPane scpInput;
    private javax.swing.JScrollPane scpLexemas;
    private javax.swing.JScrollPane scpOutput;
    private javax.swing.JTable tblLexemas;
    private javax.swing.JTextArea txtCodigo;
    private javax.swing.JLabel txtOutput;
    // End of variables declaration//GEN-END:variables
}
